### ISSUE TITLE
progress: Invoices->Actions menu is under other template

### ISSUE THREAD

**Issue by spalominor** [TreyWW/MyFinances#304]
### What version of MyFinances are you currently using?

v0.3.0

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

The first invoice menu actions work good. The second and the other have the bug.
The bug is in Mobile and Desktop
![imagen](https://github.com/TreyWW/MyFinances/assets/159827322/c7ae71b1-5625-4904-9909-b386af29b5b1)
![imagen](https://github.com/TreyWW/MyFinances/assets/159827322/869d1778-1a5c-43b9-b1dd-dd2f8e48bf00)

**Comment by spalominor** [comment]
I can do it

**Comment by wnm210** [comment]
Oops, I forgot to check that...

**Comment by davidbarrette00** [comment]
Is this still being worked on? @spalominor

**Comment by spalominor** [comment]
> Is this still being worked on? @spalominor 

Whether you want to work on this issue or want to see it fixed, currently, I am not working on it.

**Comment by TreyWW** [comment]
Anybody want to work on this? Thanks

**Comment by benluks** [comment]
Is this being worked on?

**Comment by TreyWW** [comment]
Hey @benluks apologies for the late response, I've been on holiday. This issue is still present and has no one working on it. If you'd still like to let me know, it would be much appreciated as it's an annoying bug. 

Thank you :)

**Comment by pvvramakrishnarao234** [comment]
Hey @TreyWW, I am currently working on this. Can we have a quick connect whenever you are free?

Fixed:

![image](https://github.com/user-attachments/assets/0b29fce3-952e-4af6-8b9e-997b292aa8ac)

![image](https://github.com/user-attachments/assets/844b215a-b6a7-42dc-a9c8-d15e351c4513)

**Comment by TreyWW** [comment]
Hey @pvvramakrishnarao234 thats amazing! Sure we can connect to discuss more, do you have something like discord? There's the link on our [docs](https://docs.myfinances.cloud)

**Comment by TreyWW** [comment]
DELREPLY-SAROEDVY

**Comment by TreyWW** [comment]
This issue still exists
![image](https://github.com/user-attachments/assets/c7ec5f85-44de-421a-9292-473b5eb59f32)

**Comment by JustTrying652** [comment]
Tested this on the current main branch (v0.9.4) and wasn't able to reproduce the original bug. With 5 invoices in the table, the actions dropdown for rows 2-4 opens to the left as expected, and for the last row it flips upward to avoid being clipped by the viewport — which looks like correct, intentional behavior rather than the cut-off/under-table issue shown in the original screenshots.
Could this be closed, or is there a specific scenario (screen size, browser, invoice count, etc.) where it's still reproducible? Happy to help dig further if so.
